services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - auth-service
  backend:
    build: ./be_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
  auth-service:
    build: ./auth-service
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
  postgres:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres